### ISSUE TITLE
Decide on ID generator

### ISSUE THREAD

**Issue by zet4** [arke-works/arke#1]
* https://github.com/bwmarrin/snowflake
* https://github.com/osamingo/indigo
    * Smaller IDs. (as they are encoded to base58)
    * Based on sonyflake, scaling friendly. Uses 16bit to identify node ID unlike snowflake, which allows only 1024 nodes.

**Comment by Soliel** [comment]
I'll go ahead and put my vote out for Sonyflake IDs, Sorry bwmarrin.

**Comment by liclac** [comment]
Is the idea to have all IDs (users, topics, posts, etc) generated this way? In that case, the first thing we need to consider is URLs.

Discourse topics use `/t/:slug/:id`, where `id` is sequential and `/t/:id` redirects to `/t/:slug/:id`. If we keep this format, we need typable IDs. But we could just as well make slugs unique and look up on that, I guess.

**Comment by zet4** [comment]
Pro of indigo is that the ID's are encoded using base58 and look like `tbnXgoaXVA`, base58 unlike base64 eliminates annoying characters that could confuse the user and thus are short, typable and have reduced chance of invalid input.

**Comment by zet4** [comment]
I just checked discourse's :slug, and it doesn't actually matter it seems, only the :id matters.

**Comment by albertmoravec** [comment]
Well, if we want it to be as fast as possible, I'd go with bwmarrin's one... No one's gonna type snowflake by hand anyway.

**Comment by zet4** [comment]
>No one's gonna type snowflake by hand anyway.

Are you sure?

> Discourse topics use /t/:slug/:id, where id is sequential and /t/:id redirects to /t/:slug/:id. If we keep this format, we need typable IDs. But we could just as well make slugs unique and look up on that, I guess.

**Comment by albertmoravec** [comment]
I think 10 chars long snowflakes are still too long and annoying to type by hand... But I can't think of any other solution, so I guess it will be better to leave it up to you.
